

# Production
baseURL = "https://cumulocity.com/docs"

languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Cumulocity IoT documentation"
theme = "c8ydocs"
paginate = 12
# canonifyurls = false
publishDir = "public"
# googleAnalytics = "UA-xxxxxxxx-x"
summaryLength = 30
buildFuture = true
relativeURLs = true

[taxonomies]
  sections = "section"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      style = "solarized-dark256"

[author]
  name = "Carlos Ceia @ Cumulocity"

[security]
  enableInlineShortcodes = false

[security.exec]
  allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
  osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
  getenv = ["^HUGO_"]

[security.http]
  methods = ["(?i)GET|POST"]
  urls = [".*"]

[params]

  # Global keywords configuration. Following keywords will be add to every pages
  keywords = ["Software AG", "Cumulocity IoT", "Internet of things", "analytics", "devices", "connect"]

  description = "This documentation offers comprehensive information on the var-product-c8y-iot platform both from a user and from a developer perspective. It reflects the latest state of the cloud deployment(s) of the var-product-c8y-iot platform and is continuously updated to align with recent software updates."
  
  oldguides = "//cumulocity.com/guides/welcome/intro-documentation/"

  docsPreview = false
  
  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true

  logo = "images/logo-platform.svg"


  # Your favicon path, default is "/favicon.png"
  favicon = "https://cumulocity.com/favicon.ico"

  # Content variables for Frontmatter titles
  product_c8y_iot = "Cumulocity IoT"
  company_sag = "Software AG"
  enterprise_tenant = "Enterprise tenant"

  [[params.additionalResources]]
    name = "YouTube"
    link = "https://www.youtube.com/@CumulocityIoT"
    
  [[params.additionalResources]]
    name = "Tech Community"
    link = "https://tech.forums.softwareag.com/tag/Cumulocity-IoT"
  
  [[params.additionalResources]]
    name = "Empower Portal"
    link = "https://empower.softwareag.com/"

  [[params.additionalResources]]
    name = "Product support"
    link = "https://empower.softwareag.com/"

# Customize
  [params.footer]
    copyright = "Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors. | <a href='https://www.softwareag.com/en_corporate/impressum.html'> Imprint</a> | <a href='https://www.softwareag.com/en_corporate/privacy.html'>Privacy policy</a>"
    c8ylink = "https://www.softwareag.cloud/site/product/cumulocity-iot.html"

